USE [master]
GO

/****** Object:  Database [CaveTester]    Script Date: 30/09/2018 11:13:34 ******/
CREATE DATABASE [CaveTester]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CaveTester', FILENAME = N'C:\Users\%USERNAME%\CaveTester.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CaveTester_log', FILENAME = N'C:\Users\%USERNAME%\CaveTester_log.ldf' , SIZE = 504KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [CaveTester] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CaveTester].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CaveTester] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CaveTester] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CaveTester] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CaveTester] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CaveTester] SET ARITHABORT OFF 
GO

ALTER DATABASE [CaveTester] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CaveTester] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CaveTester] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CaveTester] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CaveTester] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CaveTester] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CaveTester] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CaveTester] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CaveTester] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CaveTester] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CaveTester] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CaveTester] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CaveTester] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CaveTester] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CaveTester] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CaveTester] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CaveTester] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CaveTester] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CaveTester] SET  MULTI_USER 
GO

ALTER DATABASE [CaveTester] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CaveTester] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CaveTester] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CaveTester] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CaveTester] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CaveTester] SET QUERY_STORE = OFF
GO

USE [CaveTester]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [CaveTester] SET  READ_WRITE 
GO

